sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@^5.0.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - yarn install --force
script:
  - yarn run cover
  - yarn run check-coverage
  - yarn run build
after_success:
  - yarn run report-coverage
  - yarn run semantic-release
